create table divisas ( divisa varchar2(3) constraint pk_divisas primary key, nombre varchar2(30), simbolo varchar2(3) ) tablespace is2;
insert into divisas values ('ARS','Peso Argentino','$');
insert into divisas values ('AUD','Dolar Australiano','A$');
insert into divisas values ('BRL','Real Brasileño','R$');
insert into divisas values ('CAD','Dolar Canadiense','C$');
insert into divisas values ('CHF','Franco Suizo','Fr');
insert into divisas values ('CNY','Yuan','¥');
insert into divisas values ('CZK','Corona Checa','Kc');
insert into divisas values ('DKK','Corona Danesa','Kr');
insert into divisas values ('EUR','Euro','€');
insert into divisas values ('GBP','Libra Esterlina','£');
insert into divisas values ('HKD','Dolar de Hong Kong','HK$');
insert into divisas values ('HUF','Forinto hungaro','Ft');
insert into divisas values ('JPY','Yen Japones','¥');
insert into divisas values ('MXN','Peso Mexicano','$');
insert into divisas values ('NOK','Corona Noruega','kr');
insert into divisas values ('NZD','Dolar Neozelandes','NZ$');
insert into divisas values ('PLN','Zloty','Zt');
insert into divisas values ('SEK','Corona Sueca','kr');
insert into divisas values ('SGD','Dolar de Singapur','S$');
insert into divisas values ('USD','Dolar de Estados Unidos','$');
insert into divisas values ('ZAR','Rand','R');
